FROM openresty/openresty:1.15.8.3-2-alpine AS openresty

COPY default.conf.template /etc/nginx/conf.d/default.conf.template
COPY stream.conf.template /etc/nginx/stream.conf.template
COPY entrypoint.sh /

RUN /bin/sh -c "apk add --no-cache gettext"
RUN /bin/sh -c "echo 'include /etc/nginx/stream.conf;' >> /usr/local/openresty/nginx/conf/nginx.conf"
ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]